/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Hide the top row': '隐藏顶行',
    'Life Points': '生命点',
    'Show a row': '显示一行',
    'Loading... (If this takes too long it means there was a serious error!': '正在加载...（如果这花费的时间太长，则表示出现严重错误！',
    "Make sure that you record the time in your stream or else your speedrun won't count!": "确保您在流中记录时间，否则您的快速运行将不计算在内！",
    "my discord": "我的 discord",
    "Oh, you are still reading this?": "哦，你还在读这个吗？",
    "points": " 点数",
    "This is the end of content and the limit of break_eternity.js!": "这是内容的结束和break_eternity.js的限制！",
    "Toggle Undulating Colors": "切换波动的颜色",
    "IMPORTANT BUTTONS": "重要按钮",
    "Force toggle shift": "强制切换shift",
    "Force toggle control": "强制切换控制",
    "Attempt to fix save": "尝试修复存档",
    "Upgrades": "升级",
    "You have completed": "你已经完成了 ",
    "Current number of hotkeys": "当前热键数量",
    "If you would like to speedrun this, press Play Again.": "如果您想快速运行它，请按“再次游戏”。",
    "MAY NOT BE CORRECT OR UP TO DATE": "可能不正确或不是最新的",
    "Note by Jacorb: If anyone wishes to make a mod of this game, that is perfectly fine with me, just make sure to name it something different (ex: Prestige Tree NG+) and to let me know on": "Jacorb 的注释：如果有人想制作这个游戏的模组，我完全没问题，只要确保将其命名为不同的名称（例如：Prestige Tree NG+）并让我知道",
    "Note by pg132: You can mod my mod, just credit me lol :)": "pg132 的注释：你可以修改我的 mod，只是相信我 lol :)",
    "Original idea by papyrus (on discord)": "papyrus 的原创想法（在discord）",
    "Amoebas": "变形虫",
    "Amoebas boost Amoeba gain": "变形虫增加变形虫增益",
    "Amoebas boost point gain": "变形虫提升点数增益",
    "Currently": "当前",
    "Each Amoeba Upgrade doubles point gain": "每次 变形虫 升级都会使 点数 增加一倍",
    "Unlock the first Amoeba buyable": "解锁第一个 变形虫 可购买",
    "Each": "每个",
    "reset but gain 100% of Features on prestige per second": "重置但每秒获得 100% 的威望特性",
    "resetting at least once.": "至少重置一次。",
    "Reward": "报酬",
    "Shift to see details": "切换查看详情",
    "Square": "平方",
    "Square medal effect and": "平方奖牌效果和",
    "Start with 1e5 medals": "从 1e5 奖牌开始",
    "The above autobuyers can bulk, unlock a": "以上自动购买者可以批量，解锁一个",
    "The first five": "前五个",
    "The following only applies to layers unlocked before Goals II": "以下仅适用于在目标 II 之前解锁的层",
    "There are 5 challenges, and the first is nothing": "有5个挑战，第一个什么都没有",
    "This resets all prior Goals and all layers before and including F and their challenges": "这将重置之前的所有目标和所有层，包括 F 及其挑战",
    "This will keep you in the same challenge": "这将使您面临同样的挑战",
    "to": "到",
    "to base": "基地",
    "To get tokens in challenge 3 you need at least 1e19 Features.": "要在挑战 3 中获得代币，您至少需要 1e19 个功能。",
    "to the number of Amoeba upgrades": "到阿米巴升级的数量",
    "To unlock the ability to enter a given challenge you need to have gotten": "要解锁进入给定挑战的能力，您需要获得",
    "Tokens": "代币",
    "Unlock": "开锁",
    "Unlock a": "解锁一个",
    "Unlock a second Bacteria buyable and remove the second Amoeba effect softcap": "解锁第二个可购买的细菌并移除第二个变形虫效果软帽",
    "Unlock a seventh Amoeba buyable and raise": "解锁第七个可购买的变形虫并筹集资金",
    "Unlock a third Amoeba buyable": "解锁第三个可购买的变形虫",
    "Unlock an": "解锁一个",
    "Unlock the second Amoeba buyable": "解锁第二个可购买的变形虫",
    "Upgrades make medals multiply": "升级让奖牌成倍增加",
    "Upgrades require a certain number of tokens, but do not cost tokens": "升级需要一定数量的代币，但不需要代​​币",
    "upgrades,": "升级，",
    "upgrades, keep": "升级，保持",
    "Upon completing a challenge you get tokens for all challenges to the left and above of it": "完成挑战后，您将获得其左侧和上方所有挑战的代币",
    "which gives free levels to all": "为所有人提供免费等级",
    "which means you are in challenge 2 three times in total": "这意味着您总共参加了 3 次挑战 2",
    "You are currently in challenge": "您目前处于挑战中",
    "You can only enter challenges if you can medal reset or if you aren't in challenge 00": "只有在可以重置奖牌或未参加挑战 00 时，您才能进入挑战",
    "You get tokens per reset based on Medals gained, with the base gain being 1": "根据获得的奖牌，您每次重置都会获得代币，基本增益为 1",
    "You keep all autobuyers and they buy 10x more": "你留住所有的自动购买者，他们会多买 10 倍",
    "Doodle effect exponent": "涂鸦效果指数",
    "Double Amoeba gain and remove the ability to prestige but gain 100% of Amoebas on prestige per second": "双倍变形虫获得并移除声望的能力，但每秒获得 100% 的变形虫声望",
    "Drive": "驾驶",
    "East": "东方",
    "Easy": "简单",
    "Effect": "影响",
    "Egg": "蛋",
    "Enter": "进入",
    "Erdős": "埃尔多斯",
    "Every": "每一个",
    "Example": "例子",
    "Experience": "经验",
    "Explanation": "解释",
    "exponent": "指数",
    "Feature": "特征",
    "Fermat": "费马",
    "For example Challenge 03 means you are in challenge 0 twice and challenge 3 once": "例如，挑战 03 表示您在挑战 0 中两次，在挑战 3 中一次",
    "free": "自由",
    "Free": "自由",
    "gain and": "增益和",
    "gain exp": "获得经验",
    "gain exponent": "增益指数",
    "gain exponent and base gain": "增益指数和基数增益",
    "gain exponent and each milestone allows buyable autobuyers to buy 2x more": "获得指数，每个里程碑都允许可购买的汽车购买者购买 2 倍以上",
    "gain in challenge 4 and each upgrade adds 100 to the": "在挑战 4 中获得收益，每次升级增加 100",
    "Gain tokens and medals per second as if you prestiged": "每秒获得代币和奖章，就像您享有声望一样",
    "Get a free": "免费获得",
    "gives a free level to": "提供免费级别",
    "gives free": "免费赠送",
    "gives free levels to": "提供免费等级",
    "Goal": "目标",
    "Gödel": "哥德尔",
    "Hilbert": "希尔伯特",
    "in challenge 4": "在挑战 4",
    "Iwasawa": "岩泽",
    "Jacobsin": "雅各布辛",
    "level": "等级",
    "level per milestone": "每个里程碑级别",
    "levels": "等级",
    "levels and challenge 34 reward effects": "等级和挑战 34 种奖励效果",
    "levels and each upgrade adds .01 to the": "等级，每次升级都会增加 0.01",
    "levels, and remove": "等级，并移除",
    "levels, remove": "等级，移除",
    "linear scaling": "线性缩放",
    "linear scaling, and get a free": "线性缩放，并获得免费",
    "medal and base": "奖牌和基地",
    "medal gain and": "奖牌获得和",
    "Medals": "奖牌",
    "Milestones": "里程碑",
    "milestones require half as many goals to unlock": "里程碑需要一半的目标才能解锁",
    "NG+++ Discord": "NG+++ Discord",
    "Omnipotent I": "万能 I",
    "Omnipotent II": "万能 II",
    "Omnipotent III": "万能 III",
    "ON": "开启",
    "Once per second, automatically complete": "每秒一次，自动完成",
    "Per": "每",
    "Per milestone squared add .01 to the": "每个里程碑平方添加 .01 到",
    "Per upgrade, gain 1.1x medals and gain 1.25^upgrades more": "每次升级，获得 1.1x 奖牌并获得 1.25^升级 更多",
    "Remove the ability to": "删除能力",
    "Remove the first Amoeba effect softcap": "去掉第一个变形虫效果软上限",
    "Amount": "数量",
    "adds .01 to its base and double": "将 0.01 添加到其基数和双倍",
    "adds .01 to the": "将 .01 添加到",
    "adds levels to": "将等级添加到",
    "gain": "增益",
    "Cost": "成本",
    "Buyables": "可购买",
    "Business": "商业",
    "and adds .01 to the base": "并将 0.01 添加到基数",
    "buyable,": "可购买,",
    "buyables": "可购买",
    "buyables and each": "可购买和每个",
    "buyables cost nothing": "可购买不花钱",
    "buyables once per second and each upgrade in this row allows": "可购买 每秒一次，并且该行中的每次升级都允许",
    "buyables which both give free levels to": "都提供免费等级的可购买",
    "Each Bacteria upgrade adds .1 to the": "每次细菌升级都会增加 .1",
    "Each buyable gives free levels to all previous layers corresponding buyable": "每个可购买都为对应可购买物品的所有先前层提供免费级别",
    "effect is 1": "效果是 1",
    "Give free": "免费赠送",
    "Access gives free After levels": "访问提供免费之后级别",
    "Account": "账户",
    "Add to the": "添加到",
    "adds .001 to": "将 .001 添加到",
    "All previous layer buyables have no effect": "所有之前的层可购买都没有效果",
    "and all previous prestige effects are 1": "并且之前所有的声望效果都是1",
    "and square root point gain": "和平方根点数增益",
    "Autobuy": "自动购买",
    "can buy twice as much per upgrade in this row and unlock a fourth Amoeba buyable": "在这一行中每次升级可以购买两倍并解锁第四个可购买的变形虫",
    "challenge completion adds .1 to the": "挑战完成增加 0.1",
    "Challenge completions are not reset unless said so, and you can bulk complete challenges": "除非另有说明，否则挑战完成不会重置，您可以批量完成挑战",
    "Challenges": "挑战",
    "Completed": "已完成",
    "Keep the first two rows of Amoeba upgrades and unlock more": "保留前两排变形虫升级，解锁更多",
    "Keep the third and fourth rows of Amoeba upgrades and buy each Amoeba buyable once per second": "保持第三排和第四排变形虫升级，每秒购买每个变形虫可购买一次",
    "Remove the ability to prestige but gain 100% of Bacteria on prestige per second": "移除声望的能力，但每秒获得 100% 的细菌",
    "Unlock a Bacteria buyable and get a free": "解锁可购买的细菌并免费获得",
    "Unlock the eighth Amoeba buyable": "解锁第八个可购买的变形虫",
    "Unlock the fifth Amoeba buyable and each Amoeba upgrade gives a free": "解锁第五个可购买的变形虫，每次升级变形虫都会免费获得",
    "Unlock the final": "解锁决赛",
    "Unlock the first Bacteria challenge": "解锁第一个细菌挑战",
    "Unlock two": "解锁两个",
    "Unlock two new": "解锁两个新",
    "upgrade adds .2 to the": "升级将 .2 添加到",
    "You have completed 80 Bacteria Challenges": "您已完成 80 次细菌挑战",
    "autobuyers to buy 2x more": "自动购买者购买 2 倍以上",
    "autobuyers trigger twice as often": "自动购买者触发的频率是两倍",
    "Bacteria boosts Amoeba gain": "细菌促进阿米巴的生长",
    ", which gives free levels to all": "，它为所有人提供免费等级",
    "reset": "重置",
    "reset allows you to keep one Medal upgrade": "重置允许您保留一个奖牌升级",
    "reset allows you to keep three medal milestones": "重置允许您保留三个奖牌里程碑",
    "Rewards": "奖励",
    "Square the successfully deved boost to Max Charges": "平方成功开发的最大充电提升",
    "squared add 1 to": "平方加 1",
    "Start with 40 Rebirths and keep": "从 40 次重生开始并保持",
    "Start with 50 Rebirths and double base": "从 50 次重生和双基地开始",
    "Start with one of each token": "从每个令牌之一开始",
    "Terraria": "泰拉瑞亚",
    "Tetris": "俄罗斯方块",
    "The first row of games each generate one charge per minute.": "第一排游戏每分钟产生一次充电。",
    "There are twenty games which progressively unlock.": "有二十款游戏逐步解锁。",
    "This fail rate is purely based on how much progress you have made so far.": "这个失败率完全取决于你到目前为止取得了多少进展。",
    "Times": "时代",
    "Total": "全部的",
    "Unlock a Medal upgrade": "解锁勋章升级",
    "Unlock a Medal upgrade and unlock a": "解锁勋章升级并解锁",
    "Unlock a new row of Medal upgrades": "解锁新的一排勋章升级",
    "Unlock a row of": "解锁一排",
    "Unlock a third": "解锁第三个",
    "Unlock another row of": "解锁另一排",
    "Unlock Game Rebirth and double base": "解锁游戏重生和双基地",
    "Unlock the second Bacteria Challenge": "解锁第二个细菌挑战",
    "upgrade gives a free": "升级免费",
    "upgrade multiply base": "升级乘数基数",
    "upgrades": "升级",
    "upgrades and": "升级和",
    "upgrades and 5x the chance to succeed": "升级和 5 倍的成功机会",
    "Upon rebirthing you lose game progress.": "重生后，您将失去游戏进度。",
    "Increase the": "增加",
    "Keep": "保持",
    "Keep all Amoeba upgrades, square": "保持所有变形虫升级，平方",
    "Keep all Medal upgrades, milestones, and tokens": "保留所有勋章升级、里程碑和代币",
    "Keep one": "保留一个",
    "Keep this upgrade and make": "保持此升级并制作",
    "Keep three rows of Bacteria upgrades, raise": "保持三排细菌升级，养",
    "level and keep the fourth row of Bacteria upgrades": "等级并保持第四排细菌升级",
    "level per upgrade in this row": "此行中每次升级的等级",
    "levels and": "等级和",
    "levels and all autobuyers buy 100x more": "等级和所有自动购买者购买 100 倍以上",
    "levels and multiply Circle gain by the number of Circle upgrades": "等级并将圈子增益乘以圈子升级的数量",
    "levels and one to the": "等级和一个",
    "levels and unlock a": "等级并解锁",
    "levels and unlock the seventh": "等级并解锁第七个",
    "log(Games) boosts base medal gain": "log(Games) 提升基数奖牌增益",
    "log10(10+medals) boosts base": "log10(10+奖牌) 提升基数",
    "Max charges ^1.3": "最高收费 ^1.3",
    "milestone multiplies medal gain by 1.5": "里程碑将奖牌增益乘以 1.5",
    "milestone per": "每里程碑",
    "Minecraft": "我的世界",
    "Multiply": "乘",
    "Multiply base": "乘基",
    "no longer costs games": "不再花费游戏",
    "Omnipotent IV": "万能四",
    "Omntipotent I": "全能我",
    "Once per second attempt to Rebirth I": "每秒一次尝试重生 I",
    "Pac-man": "吃豆人",
    "Per milestone squared get an effective fully deved level and add 1 to base charge gain": "每个里程碑平方获得一个有效的完全开发等级，并在基数充电增益上增加 1",
    "Per upgrade double base": "每次升级双底",
    "Per upgrade multiply base": "每次升级乘数基数",
    "Per upgrade squared add one to": "每升级平方加一",
    "Per upgrade squared multiply base": "每次升级平方乘基",
    "Pokemon": "口袋妖怪",
    "Pong": "乒乓",
    "Portal": "传送门",
    "Press shift to see success chances.": "按 shift 查看成功机会。",
    "Raise all prior prestige gain ^1.001 and double medal gain": "提高所有先前的声望增益 ^1.001 和双倍勋章增益",
    "Raise charge gain ^1.1": "提升冲锋增益 ^1.1",
    "Raise charge gain ^1.1 and be able to automatically attempt to bulk dev each game once per second": "提高充电增益 ^1.1 并能够每秒自动尝试批量开发每个游戏一次",
    "Raise charge gain ^1.1 and buff Base G gain from rebirths": "提高冲锋增益 ^1.1 并增强重生的基数 G 增益",
    "Raise charge gain ^1.1 and shift can bulk 10x more": "提高电荷增益 ^1.1 并且移位可以增加 10 倍以上",
    "Raise charge gain ^1.1 and the first four games do not cost charges": "提升冲锋增益^1.1，前四场不消耗冲锋",
    "Raise charge gain ^1.1 and triple base": "提高电荷增益 ^1.1 和三倍基数",
    "Raise charge gain ^1.1, deving costs 10x less charges, and each Rebirth doubles max charges": "提升冲锋增益 ^1.1，开发成本降低 10 倍，每次重生使最大冲锋翻倍",
    "Raise charge gain ^1.1, triple maximum charges, and attempting to dev a game no longer costs games": "提高冲锋增益 ^1.1，三倍最大冲锋，尝试开发游戏不再花费游戏",
    "Raise charge gain ^1.2 and 6x max charges": "提高冲锋增益 ^1.2 和 6 倍最大冲锋",
    "Raise charge gain per minute ^1.2 and hold shift to attempt buy 10 clickables": "提高每分钟的充电增益 ^1.2 并按住 shift 以尝试购买 10 个可点击",
    "Raise charge gain per minute ^1.2 and sqrt(Charges) multiplies": "提高每分钟的电荷增益 ^1.2 和 sqrt(Charges) 倍增",
    "Rebirth": "重生",
    "Rebirth I": "重生 I",
    "Rebirthing makes attempting to dev harder and causes it to consume more charges.": "重生使尝试开发变得更加困难，并导致它消耗更多费用。",
    "Remove the ability to prestige but gain 100% of Circles on prestige per second": "移除声望的能力，但每秒获得 100% 的声望圈数",
    "Remove the ability to prestige but gain 100% of Doodles on prestige per second and unlock a": "移除声望的能力，但每秒获得 100% 的声望涂鸦并解锁一个",
    "Remove the ability to prestige but gain 100% of Games on prestige per second": "移除声望的能力，但每秒获得 100% 的游戏声望",
    "Remove the first Bacteria effect softcap": "去掉第一个细菌效果软帽",
    "Remove the G gain exponent softcap": "移除 G 增益指数软帽",
    "Remove the medal gain softcap and each successful dev adds .01 to the": "移除奖牌获得软上限，每个成功的开发者都会增加 0.01",
    "Remove the successful dev boost to Feature gain softcap": "移除对功能增益软上限的成功开发提升",
    "Remove the successful dev boost to Game gain softcap": "移除对游戏增益软上限的成功开发提升",
    "Remove the successful dev boost to Medal gain softcap": "取消对奖牌增益软上限的成功开发提升",
    "Requires": "需要",
    "Each attempts costs 2.08e23 charges.": "每次尝试花费 2.08e23 费用。",
    "Each Bacteria upgrade gives a free": "每次细菌升级都会免费提供",
    "Each completion gives tokens": "每个完成都会给出令牌",
    "Each milestone adds 1 to base charge gain and half an effective Rebirth level": "每个里程碑增加 1 基数充能增益和一半有效重生等级",
    "Each milestone gives two free": "每个里程碑免费赠送两个",
    "Each milestone raises max charges ^1.1 and multiply base charge gain by 1.2": "每个里程碑都会提高最大冲锋 ^1.1 并将基数冲锋增益乘以 1.2",
    "Each upgrade adds 1 to effective rebirths": "每次升级都会增加 1 次有效重生",
    "Each upgrade adds 1 to the Medal gain exponent": "每次升级都会使奖牌获得指数增加 1",
    "Each upgrade adds 78 to": "每次升级增加 78",
    "Each upgrade in this row unlocks a": "此行中的每次升级都会解锁一个",
    "Each upgrade in this row unlocks a rebirth reward": "此行的每次升级都会解锁重生奖励",
    "Each upgrade in this row unlocks an": "此行中的每次升级都会解锁一个",
    "Each upgrade multiplies base": "每次升级都会增加基数",
    "effect and double medal gain per milestone": "每个里程碑的效果和双倍奖牌增益",
    "effect exponent by +.1": "+.1 的影响指数",
    "effect to the number of Bacteria upgrades, and unlock a Amoeba buyable": "影响细菌升级数量，并解锁可购买的变形虫",
    "For the first row, you no matter what will gain a level,": "对于第一行，你无论如何都会获得一个级别，",
    "gain and you can bulk 4x more": "增益，你可以批量增加 4 倍",
    "gain base": "获得基数",
    "gain based on best": "基于最佳收益",
    "Game resetting no longer forces you into challenge 00, keep tokens, and unlock Games": "游戏重置不再强迫您挑战 00、保留代币和解锁游戏",
    "Goals multiply base": "目标倍增基数",
    "C0: Nothing": "C0：没有",
    "C1: Raise all prestige gains ^.985 + C0": "C1：提高所有声望增益^.985 + C0",
    "C2: Raise point, Egg, and Feature gain ^.9 + C1": "C2：提升点、蛋和特征增益 ^.9 + C1",
    "C3: First column buyables do not give effects in the first n layers": "C3：第一列可购买物品不会在前 n 层产生影响",
    "C4: No buyables give free levels to buyables in the first n layers": "C4：没有可购买物为前 n 层的可购买物提供免费关卡",
    "challenge": "挑战",
    "Challenge AB means you are in Challenge A twice and Challenge B once": "挑战 AB 意味着您参加了两次挑战 A 和一次挑战 B",
    "challenge and": "挑战和",
    "challenge completions squared add to the": "挑战完成平方增加",
    "challenge, and gain 100x points": "挑战，获得100倍积分",
    "challenges if you have enough points and Goals^Goals multiply": "如果你有足够的分数和目标^目标成倍增加",
    "Clicking a game will consume a charge.": "点击游戏会消耗费用。",
    "Complete a challenge by medal resetting, which requires": "通过重置奖牌完成挑战，这需要",
    "Completion": "完成",
    "Completion of a challenge gives a token to that \"upgrade\" which gives an effect": "挑战的完成会为该“升级”提供一个令牌，该“升级”会产生效果",
    "Double charge gain and holding shift allows 10x more game attempts": "双倍充电增益和保持转移允许 10 倍以上的游戏尝试",
    "Double the chance to succeed, raise charges gain ^1.1, keep": "加倍成功机会，提高冲锋获得 ^1.1，保持",
    "all prior unlocked main layers are totally reset, and goals are also reset": "所有之前解锁的主层都被完全重置，目标也被重置",
    "Always act as if you are in medal challenge 00": "总是表现得好像你在挑战奖牌 00",
    "and adds .1 to the": "并将 .1 添加到",
    "and Challenge 22 means you are in challenge 2 twice and challenge 2 once,": "挑战 22 表示您参加了两次挑战 2 和一次挑战 2，",
    "and larger buffs for completing games.": "以及用于完成游戏的更大增益。",
    "and raise": "并提高",
    "and square root": "和平方根",
    "and three rows of": "和三排",
    "and unlock a": "并解锁一个",
    "and want to enter challenge 00 to avoid softlocking": "并想进入挑战 00 以避免软锁定",
    "Autobuyers are 3x faster and buy 10x more": "自动购买者的速度提高了 3 倍，购买速度提高了 10 倍",
    "autobuyers buy 3x faster": "自动购买者的购买速度提高了 3 倍",
    "autobuyers can buy 10x more": "自动购买者可以多买 10 倍",
    "Autochess": "自走棋",
    "Automatically buy": "自动购买",
    "base and .2 to the": "基数和 .2 到",
    "base, and unlock upgrades": "基地，并解锁升级",
    "but for subsequent rows you have a non-zero chance of failing and gaining nothing.": "但是对于随后的行，您失败且一无所获的机会非零。",
    "Buy": "买",
    "buyable": "可买的",
    "buyable and": "可购买和",
    "buyable, and buyable autobuyers bulk is multiplied by medals": "可购买的，可购买的自动购买者批量乘以奖牌",
    "buyable, remove": "可购买，删除",
    "buyables cost nothing, each goal adds .002 to the": "可购买的东西不花钱，每个目标都会增加 0.002",
    "buyables don't cost anything, and keep": "可购买的东西不花任何钱，并且保持",
    "buyables once per second and": "每秒一次的可购买物品和",
    "buyables squared multiply": "可购买的平方乘",
    "buyables, unlock the final": "可买的，解锁决赛",
    "Your maximum charges is 100 and raise charge gain per minute ^1.2": "您的最大充能数为 100 并提高每分钟的充能增益 ^1.2",
    "You can also autobuy the first four games": "您还可以自动购买前四场比赛",
    "You can gain buffs by partially deving games,": "您可以通过部分开发游戏来获得增益，",
    "You can rebirth when you have fully deved 16 games.": "当您完全开发了 16 款游戏时，您可以重生。",
    "Gain one free Rebirth level": "获得一个免费的重生等级",
    ", and gain 2 charges per minute": "，并每分钟获得 2 次充电",
    "Add one to the": "添加一个到",
    "autobuyer speed": "自动购买速度",
    "level and": "水平和",
    "level and triple": "水平和三重",
    "levels and all autobuyers buy 3x faster": "水平和所有自动购买者购买速度快 3 倍",
    "levels and gain a free": "水平并获得免费",
    "ln(Charges) multiplies base": "ln(费用) 乘以基数",
    "Raise Charge gain ^1.1": "提升冲锋增益 ^1.1",
    "Raise the successfully deved boosted to Features to the 20": "将成功开发的功能提升到 20",
    "Remove the ability to prestige but gain 100% of Eggs on prestige per second and all autobuyers work 2x faster": "移除声望的能力，但每秒获得 100% 的鸡蛋声望，所有自动购买者的工作速度提高 2 倍",
    "Square the successfully deved boosted to Max Charges": "将成功开发的平方提升到最大电荷",
    "Unlock a fully completed effect": "解锁完全完成的效果",
    "upgrade multiplies base medal gain by 12 and adds 34 to the exponent": "升级将基数奖牌增益乘以 12 并在指数上增加 34",
    "upgrades, autobuy": "升级，自动购买",
    "buyable and each upgrade in this row unlocks a": "可购买，并且该行中的每次升级都会解锁一个",
    "buyables and autobuy": "可购买物品和自动购买",
    "buyables once per second": "每秒一次的可购买物品",
    "buyables once per second, and multiply all autobuyer bulk by the number of goals": "每秒一次可购买，并将所有自动购买批量乘以目标数量",
    "Details": "详情",
    "Eggs": "蛋",
    "Energy": "能源",
    "Entertainment": "娱乐",
    "Event": "事件",
    "Omnipotent V": "万能 V",
    "all prior prestige gain exponents": "所有先前的声望增益指数",
    "Click a button below to enter a challenge": "点击下方按钮进入挑战",
    "base per": "基数每",
    "boosts base": "提升基数",
    "cost and": "成本和",
    "and": "和",
    "Category": "类别",
    "base": "基数",
    "Card": "卡片",
    "Country": "国家",
    "Database": "数据库",
    "Delivery": "交付",
    "Department": "部门",
    "December": "十二月",
    "at least one token for the challenge\n                                        to the left and above": "至少一个用于挑战\n左侧和上方的代币",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Gain a free": "获得一个免费",
    "gain exponent and": "获得指数和",
    "gain exponents": "获得指数",
    "Add 1 to the": "将 1 添加到",
    "Games": "游戏",
    "Snake": "贪吃蛇",
    "Quake": "雷神",
    "Costs": "成本",
    "Gives": "给予",
    "Hearts": "心",
    "Half life": "半条命",
    "Health": "健康",
    "Valorant": "无畏契约",
    "Diablo": "暗黑破坏神",
    "Cube base Amoeba gain": "立方基础变形虫增益",
    "gain exponent and multiplies base": "获得指数并乘以基数",
    "gain per upgrade": "增益每次升级",
    "Growth": "成长",
    "can buy 10, cube": "可以购买 10 ，立方",
    "th Rebirth II reset requires having 10 + 10 * k Rebirth I": "重生 II重置需要10 + 10 * K重生我",
    "reset but gain 100% of Hearts on prestige per second": "重置，但每秒占据威望的100％",
    "Start with (9 * Rebirth II) Rebirth I upon reset": "从（9 *重生II）开始重新重置时",
    "Unlock a second": "解锁一锁",
    "upgrade act as if you have 2% less rebirths": "升级行为好像你有2％的重生",
    "upgrade adds .001 to the": "升级添加.001到了",
    "upgrade increase": "升级增加",
    "Upgrades multiply": "升级倍增",
    "However, they do not cause any nerfs, for example to Game cost.": "但是，它们不会导致任何形式，例如游戏成本。",
    "in terms of rewards. This is used for calculating completed devs and for use in upgrades.": "在奖励方面。 这用于计算已完成的DEVS和用于升级。",
    "levels and each": "水平和各个",
    "levels and per upgrade add .001 to the": "级别和每个升级添加.001到",
    "levels and raise completed games to Features boost ^500": "级别并将完成的游戏提升到功能^ 500",
    "levels and raise completed games to Games boost ^50": "水平并将完成的游戏提升到游戏升高^ 50",
    "Per upgrade per medal upgrade get two free effecitve completed devs and unlock an": "每个奖金升级升级获得两个免费的Effecitve完成了Devs并解锁了",
    "Raise successful devs boost to Games to the number of": "提升成功的DEVS向游戏提升到游戏",
    "Raise the": "提高",
    "Rebirth II": "重生 II",
    "Rebirth II and all further rebirths count as 10 of the previous rebirths": "重生II和所有进一步的重生统计到以前的重生",
    "Rebirth III": "重生 III",
    "Rebirth IV": "重生 IV",
    "reset but gain 100% of Hearts on prestige per second": "重置，但每秒占据威望的100％",
    "Lock": "锁",
    "Filter": "过滤",
    "Puzzle": "拼图",
    "Tin Key": "锡钥匙",
    "allows you to buy twice as many buyables from": "允许您购买两倍的可购买商品",
    "Achievements multiply knowledge gain, unlock a": "成就倍增知识增益，解锁一个",
    "and banked exp gain": "和银行经验收益",
    "and before": "和之前",
    "and Knowledge": "和知识",
    "at a time and square": "在同一时刻并且平方",
    "Autobuy the last row of locks, each": "自动购买最后一排锁，每个",
    "base and": "基数和",
    "base and unlock another Lock": "基地并解锁另一个锁",
    "base effect to the number of": "对数量的基础效应",
    "base effects": "基础效应",
    "base to the number of": "以数量为基础",
    "Best knowledge": "最好的知识",
    "Buff India to all but one and attempt to buy Larger Puzzle without cost once per second": "Buff India 对除了一个以外的所有人，并尝试每秒一次免费购买更大的拼图",
    "buyable, and remove": "可购买并删除",
    "challenge and you buy 1000x Puzzle and Key content": "挑战，您购买 1000 倍拼图和关键内容",
    "challenge completion doubles banked exp gain": "挑战完成使银行经验收益翻倍",
    "challenge completion gives a free": "挑战完成提供免费",
    "challenge completion past 170 get 4x": "挑战完成超过 170 次获得 4 倍",
    "challenge completions": "挑战完成",
    "challenge completions and add 1 to the": "挑战完成并将 1 添加到",
    "challenge completions per": "挑战完成次数",
    "challenge per 3": "每 3 次挑战",
    "challenges": "挑战",
    "challenges after 5 are halved and unlock another": "5 之后的挑战减半并解锁另一个",
    "challenges and unlock the final": "挑战并解锁决赛",
    "Coal": "煤炭",
    "Coal Lock": "煤锁",
    "Copper": "铜",
    "Each Key raises point gain to 1 + [Diamond Keys] / 100 and triple lock autobuyer speed": "每个钥匙将积分增益提高到 1 + [钻石钥匙] / 100 和三重锁定自动购买速度",
    "Each mine multiplies knowledge gain by 1.1": "每个地雷将知识增益乘以 1.1",
    "Each upgrade gives 10x Knowledge gain and adds .01 to the": "每次升级都会获得 10 倍的知识增益并增加 0.01",
    "Each upgrade multiplies mine gain by 10 and you can buy 10x Bulk Amount": "每次升级都会使我的收益乘以 10，您可以购买 10 倍批量",
    "effect": "影响",
    "effect exponent": "效应指数",
    "effect softcap": "效果软帽",
    "effects": "效果",
    "effects knowledge and you can complete 5 more of each": "效果知识，你可以完成5个以上",
    "effects, -.05 effective": "效果，-.05 有效",
    "gain and per completion past 178 get an effective lock": "获得和每完成 178 次获得有效锁",
    "gain and you can complete 1 more": "获得，您可以再完成 1 个",
    "gain exponent and multiply Osmium gain by the number of reset": "增益指数并将锇增益乘以复位次数",
    "gain per Key": "每键增益",
    "gain per milestone, and achievements multiply banked exp gain": "每个里程碑的增益，成就乘以银行经验增益",
    "Omnipotent VI": "万能 VI",
    "Omnipotent VII": "万能 VII",
    "per milestone, and unlock a key": "每个里程碑，并解锁一个钥匙",
    "Per upgrade in this row unlock an": "此行中的每次升级解锁一个",
    "Titanium Key": "钛金钥匙",
    "Tungsten Key": "钨钥匙",
    "upgrades and get an effective": "升级并获得有效",
    "Remove the ability to prestige, but gain 100% of Missions upon reset per second and triple Mission gain": "移除声望的能力，但在每秒重置时获得 100% 的任务和三倍的任务增益",
    "Start": "开始",
    "Knowledge": "知识",
    "Larger Puzzle": "更大的拼图",
    "Add to": "添加到",
    "and remove": "并移除",
    "milestones, triple base": "里程碑，三重基地",
    "Mine": "矿山",
    "Multiply Lemon gain per Key": "每个键乘以柠檬增益",
    "Osmium": "锇",
    "Per milestone you can complete one more": "每个里程碑你可以再完成一个",
    "Per milestone you get ten": "每个里程碑你得到十个",
    "Remove the ability to prestige but gain 100% of Keys upon prestige per second, and each milestone doubles": "移除声望的能力，但每秒获得声望时 100% 的钥匙，每个里程碑加倍",
    "Remove the ability to prestige for Lemons, but gain 100% of Lemons on reset per second": "移除柠檬威望的能力，但每秒重置时获得 100% 的柠檬",
    "Reset": "重置",
    "resets nothing and unlock a": "什么都不重置并解锁",
    "Silver": "银",
    "The first ten keys cost their own resources": "前十个键会消耗自己的资源",
    "They do not cause you to lose lock effects, and give additional effects.": "它们不会使您失去锁定效果，并提供额外的效果。",
    "Tin": "锡",
    "Titanium": "钛",
    "Tungsten": "钨",
    "Tungsten multiplies": "钨倍增",
    "upgrades, double bulk amount, and square Bulk Amount": "升级、双倍批量和平方批量",
    "while the last five cost higher and higher layers' resources.": "而最后五个成本越来越高的层资源。",
    "You can buy 10 levels of": "您可以购买 10 个级别的",
    "You have completed 91 Key Challenges": "您已完成 91 项关键挑战",
    "Diamond": "钻石",
    "Diamond Keys": "钻石钥匙",
    "gain exponent and effective": "获得指数和有效",
    "Give free effective Keys [first two rows]": "赠送免费有效钥匙【前两行】",
    "Gold": "金子",
    "Iron": "铁",
    "Idea": "主意",
    "Keep Bulk Amount levels upon reset and once per second get Success Chance levels as if you bought max, but it doesn't cost Knowledge": "重置时保持批量级别，每秒一次获得成功机会级别，就像您购买了最大值一样，但它不消耗知识",
    "Key": "钥匙",
    "Keys": "钥匙",
    "Keys require having enough Locks unlocked.": "钥匙需要有足够多的锁解锁。",
    "Lock content autobuyers are three times as fast and square Tungsten effect": "锁定内容自动购买者 是三倍的速度和平方 钨 效果",
    "Master Lock": "玛斯特锁",
    "milestones": "里程碑",
    "reset you keep two": "重置你保留两个",
    "squares": "平方",
    "squares point gain": "平方点增益",
    "times and unlock a autobuyer for the first two rows of locks": "次并为前两排锁解锁自动购买者",
    "Tin Lock": "锡锁",
    "Titanium Lock": "钛锁",
    "Unlock an autobuyer that buys each mine once per second and each milestone gives 4x metal gain": "解锁一个自动购买者，每秒购买每个矿山一次，每个里程碑都会获得 4 倍的金属收益",
    "Unlock another": "解锁另一个",
    "Unlock the final Lock and each": "解锁最后的锁和每个",
    "upgrades and multiply": "升级和倍增",
    "upgrades and raise": "升级和提高",
    "You autobuy": "你自动购买",
    "You buy 1000x Bulk Amount, autobuy the last row of puzzle upgrades, and you can complete one more": "您购买1000x 批量数量，自动购买最后一排拼图升级，您可以再完成一个",
    "You can complete 2 more": "您还可以完成 2 个",
    "You start with 98% of your best puzzle completions over all time and unlock an": "您从 98% 的最佳拼图完成开始，然后解锁一个",
    "and unlock the last": "并解锁最后一个",
    "base ^1.01 per milestone": "每个里程碑的基础 ^1.01",
    "buyable and a new row of": "可买的和新的一排",
    "buyable and multiply base": "可购买和乘法基础",
    "buyable autobuyer and an": "可购买的自动购买者和",
    "buyables and": "可买的和",
    "challenge and each": "挑战和每个",
    "challenge completion adds 5 to the": "挑战完成增加 5 到",
    "challenge multiples mine production by [": "通过[挑战倍数矿山生产",
    "challenge per milestone": "每个里程碑的挑战",
    "challenges per upgrade and you automatically complete": "每次升级的挑战，你会自动完成",
    "challenges]/100 (at least 1": "挑战]/100（至少 1",
    "Coal Key": "煤钥匙",
    "Copper Key": "铜钥匙",
    "Diamond Key": "钻石钥匙",
    "Diamond Locks": "钻石锁",
    "Each milestone adds .2 to the": "每个里程碑都会增加 0.2",
    "effect by 1.2": "1.2的效果",
    "effect by the number of upgrades squared": "升级次数平方的影响",
    "effect to the 1.3": "对1.3的影响",
    "effect to the number of": "对数量的影响",
    "effect to the number of locks (at least 1) and per upgrade in this row unlock a": "影响锁的数量（至少 1 个），并且在该行中每次升级解锁一个",
    "effect to the sqrt(number of upgrades) and each": "对 sqrt（升级次数）和每个",
    "effect, and unlock 3": "效果，并解锁3",
    "effects base": "效果基础",
    "effects mine gain and multiply": "影响地雷增益和倍增",
    "gain and you buy 10x puzzle buyables": "获得并且您购买了 10 倍的拼图可购买物品",
    "gain exponent, and": "获得指数，并且",
    "Gold Lock": "金锁",
    "Iron Lock": "铁锁",
    "Keep Puzzle upgrades upon reset and each milestone adds .1 to the": "重置时保持拼图升级，每个里程碑都会增加 0.1",
    "Keep reset": "保持重置",
    "Keeping": "保持",
    "Keeps": "保持",
    "Lemons": "柠檬",
    "Location": "位置",
    "Raise": "提高",
    "Improve": "提升",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "This is my (pg132's) first fully completed mod, I may have another coming. Consider playing the other game I currently dev, AD NG+++: ": "这是我（pg132 的）第一个完全完成的 mod，我可能还会有另一个。 考虑玩我目前开发的另一个游戏，AD NG+++：",
    "The Prestige Tree made by Jacorb and Aarex": "Jacorb 和 Aarex 制作的声望树",
    "Change log": "更新日志",
    "Congratulations! You have reached the end and beaten this game!": "恭喜！ 你已经到达终点并通关了本游戏！",
    "Endgame: 378 achievements": "残局：378 项成就",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
//    'ON': '打开',
    'On': '打开',
    'Off': '关闭',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置',
    'Nine': '9',
    'Nineteen': '19',
    'One': '1',
    'Seven': '7',
    'Seventeen': '17',
    'Thirteen': '13',
    'Sixteen': '16',
    'Ten': '10',
    'Thirty': '30',
    'eight': '8',
    'five': '5',
    'four': '4',
    'nine': '9',
    'one': '1',
    'seven': '7',
    'six': '6',
    'three': '3',
    'two': '2',
    'Three': '3',
    'Twelve': '12',
    'Twenty': '20',
    'Two': '2',
    'Fourteen': '14',
    'Four': '4',
    'Six': '6',
    'Fifty': '50',
    'Fifteen': '15',
    'Eighteen': '18',
    'Eleven': '11',
    'Five': '5',
    'Forty': '40',
    'Ninety': '90',
    'Seventy': '70',
    'Sixty': '60',
    'Eighty': '80',
    'One': '01',
    'Two': '02',
    'Three': '03',
    'Four': '04',
    'Five': '05',
    'Six': '06',
    'Seven': '07',
    'Eight': '08',
    'Nine': '09',
    'Four Hundred': '4',
    'One Hundred': '100',
    'Two Hundred': '200',
    'Three Hundred': '300',
    'Five Hundred': '500',
    'Six Hundred': '600',
    'Seven Hundred': '700',
    'DNA': 'DNA',
    'Micro': 'Micro',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\t\t\t\t\t\t\t": "\t\t\t\t\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t": "\t\t\t",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "There is a two second cooldown for prestiging (": "声望有两秒的冷却时间（",
    ", which buffs point and all previous prestige gain by ": ", 增益点和之前的所有声望都会增加",
    "Each Amoeba Upgrade multiplies Amoeba gain by ": "每次 变形虫 升级都会使 变形虫 增益乘以",
    "Shift/Control Mode:": "变速/控制模式：",
    "Add one to the medal gain exponent (": "将奖牌增益指数加1（",
    "adds .0001 to the": "将 0.0001 添加到",
    "Baby": "婴儿",
    "Dev Speed:": "开发速度：",
    "Features": "功能",
    "• ": "• ",
    "Percent complete with this puzzle (est time ": "完成这个拼图的百分比（估计时间 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "One Hundred and ": "1",
    "Seven Hundred and ": "7",
    "Thirty-": "3",
    "Twenty-": "2",
    "Forty-": "4",
    "Eighty-": "8",
    "Ninety-": "9",
    "Fifty-": "5",
    "Seventy-": "7",
    "Sixty-": "6",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n\t\t": "\n\t\t",
    "\n": "",
    "/sec": "/秒",
    " nice": " 不错",
    " affects Life Points": "影响生命点",
    ") times multipliers": ") 次乘数",
    "\n\t\t\t": "\n\t\t\t",
    "\n\t\t\t\t": "\n\t\t\t\t",
    "Each challenge has a reward, and upon claiming said reward": "每个挑战都有一个奖励，并在领取所述奖励时",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\)\*([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^\*([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e(\d+) µ$/,
    /^([\d\.]+)e(\d+) OOMs$/,
    /^([\d\.]+)e(\d+) 细胞$/,
    /^([\d\.]+)e(\d+) 干细胞$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)\/m$/,
    /^([\d\.]+)\/h$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)ms$/,
    /^([\d\.]+)$/,
    /^C([\d\.]+)$/,
    /^e([\d\.,]+)$/,
    /^EXTREME: (.+)$/,
    /^α → (.+)$/,
    /^β → (.+)$/,
    /^𝛾 → (.+)$/,
    /^µ → (.+)$/,
    /^([\d\.]+)\^x$/,
    /^\(([\d\.,]+)$/,
    /^([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^\^e([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+) µ$/,
    /^([\d\.]+)e([\d\.,]+) µ$/,
    /^ee([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^\*e([\d\.]+)e([\d\.,]+) to$/, '\*e$1e$2 到'],
    [/^Requires: (.+) Cells$/, '要求：$1 细胞'],
    [/^Last save was (.+)s ago.$/, '上次保存是在 $1 秒前。'],
    [/^Last save was (.+)s ago. Average TPS (.+).$/, '上次保存是在 $1 秒前。 平均 $2。'],
    [/^Get a (.+) Gem$/, '获得 1个 $1 宝石'],
    [/^Reset for (.+) Hearts$/, '重置为 $1 心'],
    [/^Reset for (.+) Amoebas$/, '重置为 $1 变形虫'],
    [/^You are gaining (.+) Hearts per second$/, '你每秒获得 $1 心'],
    [/^You are gaining (.+) Lemons per second$/, '你每秒获得 $1 柠檬'],
    [/^You are gaining (.+) Missions per second$/, '你每秒获得 $1 任务'],
    [/^You are gaining (.+) Keys per second and hold shift to see costs$/, '您每秒获得 $1 钥匙并按住 shift 以查看成本'],
    [/^You have done (.+) Amoeba resets$/, '您已完成 $1 次变形虫重置'],
    [/^Each Amoeba upgrade adds (.+) to the$/, '每次 变形虫 升级都会增加 $1 到'],
    [/^Each upgrade adds (.+) to the$/, '每次升级都会增加 $1 到'],
    [/^([\d\.]+) effective$/, '$1 有效'],
    [/^([\d\.,]+) effective prior Keys$/, '$1 有效的优先钥匙'],
    [/^([\d\.,]+) effective locks$/, '$1 有效锁'],
    [/^([\d\.,]+) charges per minute$/, '$1 收费每分钟'],
    [/^e([\d\.]+)e([\d\.,]+) Doodles$/, 'e$1e$2 涂鸦'],
    [/^e([\d\.]+)e([\d\.,]+) Circles$/, 'e$1e$2 圆圈'],
    [/^e([\d\.]+)e([\d\.,]+) Bacteria$/, 'e$1e$2 细菌'],
    [/^\+([\d\.]+) Free successfully deved games$/, '\+$1 免费成功开发的游戏'],
    [/^\+([\d\.]+) Access base$/, '\+$1 访问基数'],
    [/^\+([\d\.]+) Brand base$/, '\+$1 品牌基数'],
    [/^\+([\d\.]+) to Effective Completed Games$/, '\+$1 到 有效的已完成游戏'],
    [/^\+([\d\.]+) to G gain exponent$/, '\+$1 到 G 增益指数'],
    [/^\+([\d\.]+) to F gain exponent$/, '\+$1 到 F 增益指数'],
    [/^\+([\d\.]+) to$/, '\+$1 到'],
    [/^\*([\d\.]+) to$/, '\*$1 到'],
    [/^\^([\d\.]+) Are effect$/, '\^$1 效果'],
    [/^\^([\d\.]+) to all mine gain$/, '\^$1 到全部矿山增益'],
    [/^\*e([\d\.]+)e([\d\.,]+) Circle effect$/, '\*e$1e$2 圆圈效果'],
    [/^\*e([\d\.]+)e([\d\.,]+) Baby base$/, '\*e$1e$2 婴儿基数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Eggs$/, '\*e$1e$2 蛋'],
    [/^\*e([\d\.]+)e([\d\.,]+) Due base$/, '\*e$1e$2 正当基数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Category base$/, '\*e$1e$2 类别基数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Against base$/, '\*e$1e$2 反对基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) Because base$/, '\*e$1e$2 原因基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) Because base$/, '\*e$1e$2 原因基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) Circles$/, '\*e$1e$2 圈子'],
    [/^\*e([\d\.]+)e([\d\.,]+) Advanced base$/, '\*e$1e$2 高级基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) points$/, '\*e$1e$2 点数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Bacteria$/, '\*e$1e$2 细菌'],
    [/^\*e([\d\.]+)e([\d\.,]+) Amoebas$/, '\*e$1e$2 变形虫'],
    [/^\*([\d\.]+) mine production per mine$/, '\*$1 矿山生产每个矿山'],
    [/^\*([\d\.]+)e([\d\.,]+) to Effective Completed Games$/, '\*$1e$2 到 有效的已完成游戏'],
    [/^\*([\d\.]+)e([\d\.,]+) to G gain exponent$/, '\*$1e$2 到 G 增益指数'],
    [/^\*([\d\.]+)e([\d\.,]+) to F gain exponent$/, '\*$1e$2 到 F 增益指数'],
    [/^\*([\d\.]+)e([\d\.,]+) to Base F Gain$/, '\*$1e$2 到 基础 F 增益'],
    [/^\*([\d\.]+)e([\d\.,]+) to Base G Gain$/, '\*$1e$2 到 基础 G 增益'],
    [/^\*([\d\.]+)e([\d\.,]+) to Games$/, '\*$1e$2 到 游戏'],
    [/^\*([\d\.]+)e([\d\.,]+) to Max Charges$/, '\*$1e$2 到 最高收费'],
    [/^\*([\d\.]+)e([\d\.,]+) to Features$/, '\*$1e$2 到 功能'],
    [/^\*([\d\.]+)e([\d\.,]+) to Medals$/, '\*$1e$2 到 奖牌'],
    [/^\*([\d\.]+)e([\d\.,]+) to Manual Bulk$/, '\*$1e$2 到 手动批量'],
    [/^\*([\d\.]+)e([\d\.,]+) to Base G Gain$/, '\*$1e$2 到 基础 G 增益'],
    [/^\*([\d\.,]+) to Manual Bulk$/, '\*$1 到 手动批量'],
    [/^Currently: \*([\d\.]+)e([\d\.,]+)$/, '当前：\*$1e$2'],
    [/^\*([\d\.]+)e([\d\.,]+) knowledge per Key$/, '\*$1e$2 知识 每 钥匙'],
    [/^\*([\d\.]+)e([\d\.,]+) knowledge per key$/, '\*$1e$2 知识 每 钥匙'],
    [/^\*([\d\.]+)e([\d\.,]+) mine gain per Key$/, '\*$1e$2 矿山增益 每 钥匙'],
    [/^\*([\d\.]+)e([\d\.,]+) mine production per$/, '\*$1e$2 矿山生产 每'],
    [/^\*([\d\.]+)e([\d\.,]+) global mine production per Lock$/, '\*$1e$2 全局 矿山生产 每个 锁'],
    [/^\*([\d\.]+)e([\d\.,]+) Card base$/, '\*$1e$2 卡片基数'],
    [/^\*([\d\.]+)e([\d\.,]+) Omnipotent III base$/, '\*$1e$2 万能 III 基数'],
    [/^\*([\d\.]+)e([\d\.,]+) Department base$/, '\*$1e$2 部门 基数'],
    [/^\*([\d\.]+)e([\d\.,]+) Drive base$/, '\*$1e$2 驾驶 基数'],
    [/^\*([\d\.]+)e([\d\.,]+) Features$/, '\*$1e$2 功能'],
    [/^\*([\d\.]+)e([\d\.,]+) base Bacteria gain$/, '\*$1e$2 基本细菌增益'],
    [/^\*([\d\.]+)e([\d\.,]+) Call base$/, '\*$1e$2 呼叫基数'],
    [/^\*([\d\.]+)e([\d\.,]+) Doodles$/, '\*$1e$2 涂鸦'],
    [/^\*([\d\.]+)e([\d\.,]+) Beauty base$/, '\*$1e$2 美丽基数'],
    [/^\+([\d\.]+)e([\d\.,]+) Example base$/, '\+$1e$2 示例基地'],
    [/^\+([\d\.]+)e([\d\.,]+) Doodle gain exponent$/, '\+$1e$2 涂鸦增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) Egg gain exponent$/, '\+$1e$2 蛋增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) Access base$/, '\+$1e$2 访问基地'],
    [/^\+([\d\.]+)e([\d\.,]+) Circle gain exponent$/, '\+$1e$2 圆圈增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) Amoeba gain exponent$/, '\+$1e$2 变形虫增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) B gain exp$/, '\+$1e$2 B 增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) to Max Charges$/, '\+$1e$2 到 最高收费'],
    [/^You are gaining (.+) Games per second$/, '您每秒获得 $1 游戏'],
    [/^You are gaining (.+) Features per second$/, '您每秒获得 $1 功能'],
    [/^You have (.+) charges and are gaining (.+) per second.$/, '你有 $1 充能，每秒获得 $2。'],
    [/^You have (.+) games, (.+) medals, (.+) goals, and (.+) features.$/, '您有 $1 场比赛、$2 枚奖牌、$3 个进球和 $4 个特征。'],
    [/^You have successfully deved (.+) games so$/, '您已经成功开发了 $1 款游戏，所以'],
    [/^You have rebirthed (.+) times.$/, '你重生了 $1 次。'],
    [/^You have rebirthed (.+) times so$/, '你重生了 $1 次所以'],
    [/^You have fully completed (.+) games so$/, '你已经完全完成了 $1 场比赛所以'],
    [/^You have done (.+) Heart resets$/, '你已经完成了 $1 次心脏重置'],
    [/^You have completed (.+) Circle Challenges$/, '您已完成 40 个圈子挑战'],
    [/^You are gaining (.+) Eggs per second$/, '您每秒获得 $1 鸡蛋'],
    [/^and (.+) tokens$/, '和 $1 代币'],
    [/^gain, currently: (.+)$/, '增益，当前：$1'],
    [/^gain by ([\d\.]+)$/, '增益 $1'],
    [/^Reset for (.+) Medals$/, '重置为 $1 奖牌'],
    [/^Next at (.+) Games$/, '下一个在 $1 游戏'],
    [/^Next at (.+) points$/, '下一个在 $1 点'],
    [/^Get (.+) Organs$/, '获得 $1 器官'],
    [/^([\d\.]+) effective Locks per$/, '$1 每个有效的锁'],
    [/^gain by ([\d\.]+)e([\d\.,]+)$/, '增益 $1e$2'],
    [/^([\d\.]+)e([\d\.,]+) Features$/, '$1e$2 功能'],
    [/^([\d\.]+)e([\d\.,]+) Games$/, '$1e$2 游戏'],
    [/^([\d\.]+)e([\d\.,]+) Missions$/, '$1e$2 任务'],
    [/^e([\d\.]+)e([\d\.,]+) Games$/, 'e$1e$2 游戏'],
    [/^e([\d\.]+)e([\d\.,]+) Keys$/, 'e$1e$2 钥匙'],
    [/^e([\d\.]+)e([\d\.,]+) Features$/, 'e$1e$2 功能'],
    [/^e([\d\.]+)e([\d\.,]+) Medals$/, 'e$1e$2 奖牌'],
    [/^e([\d\.]+)e([\d\.,]+) Eggs$/, 'e$1e$2 蛋'],
    [/^e([\d\.]+)e([\d\.,]+) Amoebas$/, 'e$1e$2 变形虫'],
    [/^Gems: (.+)$/, '宝石：$1'],
    [/^Get (.+) Dilation completions$/, '获得 $1 扩张完成'],
    [/^Get (.+) Oxygenated Blood$/, '获得 $1 含氧血'],
    [/^Get (.+) Hydrogen$/, '获得 $1 氢'],
    [/^Get (.+) Atomic Hydrogen$/, '获得 $1 原子氢'],
    [/^Requires: ([\d\.,]+) Keys$/, '需要: $1 钥匙'],
    [/^Requires: ([\d\.,]+) Mission$/, '需要: $1 任务'],
    [/^Requires: (.+) Missions$/, '需要: $1 任务'],
    [/^Requires: (.+) Keys$/, '需要: $1 钥匙'],
    [/^Requires: (.+) Lemons$/, '需要: $1 柠檬'],
    [/^Requires: ([\d\.,]+) Completed games$/, '需要: $1 已完成的游戏'],
    [/^Requires: ([\d\.,]+) Key$/, '需要: $1 钥匙'],
    [/^Requires: ([\d\.,]+) Lemon$/, '需要: $1 柠檬'],
    [/^Requires: ([\d\.,]+) Games$/, '需要: $1 游戏'],
    [/^Requires: ([\d\.,]+) ([\d\.,]+) Token$/, '需要: $1 $2 代币'],
    [/^Requires: ([\d\.,]+) Successful devs$/, '需要: $1 成功的开发者'],
    [/^Requires: ([\d\.,]+) Medal$/, '需要: $1 奖章'],
    [/^Requires: ([\d\.,]+) Hearts$/, '需要: $1 心'],
    [/^Requires: ([\d\.,]+) Medals$/, '需要: $1 奖牌'],
    [/^Requires: ([\d\.,]+) Rebirth I$/, '需要: $1 重生 I'],
    [/^Requires: ([\d\.,]+)\% Completion on Portal$/, '需要: $1\% 在传送门上完成'],
    [/^Requires: ([\d\.,]+) ([\d\.,]+) Tokens$/, '需要: $1 $2 代币'],
    [/^Cost: ([\d\.,]+)$/, '成本: $1'],
    [/^Cost: ([\d\.,]+) $/, '成本: $1 '],
    [/^Cost: ([\d\.]+)e([\d\.,]+)$/, '成本: $1e$2'],
    [/^Cost: ([\d\.]+)e([\d\.,]+) $/, '成本: $1e$2 '],
    [/^Cost: e([\d\.]+)e([\d\.,]+) $/, '成本: e$1e$2 '],
    [/^Goal: e([\d\.]+)e([\d\.,]+) points$/, '目标: e$1e$2 点数'],
    [/^Goal: ee([\d\.]+)e([\d\.,]+) points$/, '目标: ee$1e$2 点数'],
    [/^Cost: (.+) Deuterium$/, '成本: $1 氘'],
    [/^Cost: (.+) Organs$/, '成本: $1 器官'],
    [/^Time Played: (.+)s$/, '游戏时长：$1 秒'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);