/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Hide the top row': '隐藏顶行',
    'Life Points': '生命点',
    'Show a row': '显示一行',
    'Loading... (If this takes too long it means there was a serious error!': '正在加载...（如果这花费的时间太长，则表示出现严重错误！',
    "Make sure that you record the time in your stream or else your speedrun won't count!": "确保您在流中记录时间，否则您的快速运行将不计算在内！",
    "my discord": "我的 discord",
    "Oh, you are still reading this?": "哦，你还在读这个吗？",
    "points": " 点数",
    "This is the end of content and the limit of break_eternity.js!": "这是内容的结束和break_eternity.js的限制！",
    "Toggle Undulating Colors": "切换波动的颜色",
    "IMPORTANT BUTTONS": "重要按钮",
    "Force toggle shift": "强制切换shift",
    "Force toggle control": "强制切换控制",
    "Attempt to fix save": "尝试修复存档",
    "Upgrades": "升级",
    "You have completed": "你已经完成了 ",
    "Current number of hotkeys": "当前热键数量",
    "If you would like to speedrun this, press Play Again.": "如果您想快速运行它，请按“再次游戏”。",
    "MAY NOT BE CORRECT OR UP TO DATE": "可能不正确或不是最新的",
    "Note by Jacorb: If anyone wishes to make a mod of this game, that is perfectly fine with me, just make sure to name it something different (ex: Prestige Tree NG+) and to let me know on": "Jacorb 的注释：如果有人想制作这个游戏的模组，我完全没问题，只要确保将其命名为不同的名称（例如：Prestige Tree NG+）并让我知道",
    "Note by pg132: You can mod my mod, just credit me lol :)": "pg132 的注释：你可以修改我的 mod，只是相信我 lol :)",
    "Original idea by papyrus (on discord)": "papyrus 的原创想法（在discord）",
    "Amoebas": "变形虫",
    "Amoebas boost Amoeba gain": "变形虫增加变形虫增益",
    "Amoebas boost point gain": "变形虫提升点数增益",
    "Currently": "当前",
    "Each Amoeba Upgrade doubles point gain": "每次 变形虫 升级都会使 点数 增加一倍",
    "Unlock the first Amoeba buyable": "解锁第一个 变形虫 可购买",
    "Each": "每个",
    "reset but gain 100% of Features on prestige per second": "重置但每秒获得 100% 的威望特性",
    "resetting at least once.": "至少重置一次。",
    "Reward": "报酬",
    "Shift to see details": "切换查看详情",
    "Square": "平方",
    "Square medal effect and": "平方奖牌效果和",
    "Start with 1e5 medals": "从 1e5 奖牌开始",
    "The above autobuyers can bulk, unlock a": "以上自动购买者可以批量，解锁一个",
    "The first five": "前五个",
    "The following only applies to layers unlocked before Goals II": "以下仅适用于在目标 II 之前解锁的层",
    "There are 5 challenges, and the first is nothing": "有5个挑战，第一个什么都没有",
    "This resets all prior Goals and all layers before and including F and their challenges": "这将重置之前的所有目标和所有层，包括 F 及其挑战",
    "This will keep you in the same challenge": "这将使您面临同样的挑战",
    "to": "到",
    "to base": "基地",
    "To get tokens in challenge 3 you need at least 1e19 Features.": "要在挑战 3 中获得代币，您至少需要 1e19 个功能。",
    "to the number of Amoeba upgrades": "到阿米巴升级的数量",
    "To unlock the ability to enter a given challenge you need to have gotten": "要解锁进入给定挑战的能力，您需要获得",
    "Tokens": "代币",
    "Unlock": "开锁",
    "Unlock a": "解锁一个",
    "Unlock a second Bacteria buyable and remove the second Amoeba effect softcap": "解锁第二个可购买的细菌并移除第二个变形虫效果软帽",
    "Unlock a seventh Amoeba buyable and raise": "解锁第七个可购买的变形虫并筹集资金",
    "Unlock a third Amoeba buyable": "解锁第三个可购买的变形虫",
    "Unlock an": "解锁一个",
    "Unlock the second Amoeba buyable": "解锁第二个可购买的变形虫",
    "Upgrades make medals multiply": "升级让奖牌成倍增加",
    "Upgrades require a certain number of tokens, but do not cost tokens": "升级需要一定数量的代币，但不需要代​​币",
    "upgrades,": "升级，",
    "upgrades, keep": "升级，保持",
    "Upon completing a challenge you get tokens for all challenges to the left and above of it": "完成挑战后，您将获得其左侧和上方所有挑战的代币",
    "which gives free levels to all": "为所有人提供免费等级",
    "which means you are in challenge 2 three times in total": "这意味着您总共参加了 3 次挑战 2",
    "You are currently in challenge": "您目前处于挑战中",
    "You can only enter challenges if you can medal reset or if you aren't in challenge 00": "只有在可以重置奖牌或未参加挑战 00 时，您才能进入挑战",
    "You get tokens per reset based on Medals gained, with the base gain being 1": "根据获得的奖牌，您每次重置都会获得代币，基本增益为 1",
    "You keep all autobuyers and they buy 10x more": "你留住所有的自动购买者，他们会多买 10 倍",
    "Doodle effect exponent": "涂鸦效果指数",
    "Double Amoeba gain and remove the ability to prestige but gain 100% of Amoebas on prestige per second": "双倍变形虫获得并移除声望的能力，但每秒获得 100% 的变形虫声望",
    "Drive": "驾驶",
    "East": "东方",
    "Easy": "简单",
    "Effect": "影响",
    "Egg": "蛋",
    "Enter": "进入",
    "Erdős": "埃尔多斯",
    "Every": "每一个",
    "Example": "例子",
    "Experience": "经验",
    "Explanation": "解释",
    "exponent": "指数",
    "Feature": "特征",
    "Fermat": "费马",
    "For example Challenge 03 means you are in challenge 0 twice and challenge 3 once": "例如，挑战 03 表示您在挑战 0 中两次，在挑战 3 中一次",
    "free": "自由",
    "Free": "自由",
    "gain and": "增益和",
    "gain exp": "获得经验",
    "gain exponent": "增益指数",
    "gain exponent and base gain": "增益指数和基数增益",
    "gain exponent and each milestone allows buyable autobuyers to buy 2x more": "获得指数，每个里程碑都允许可购买的汽车购买者购买 2 倍以上",
    "gain in challenge 4 and each upgrade adds 100 to the": "在挑战 4 中获得收益，每次升级增加 100",
    "Gain tokens and medals per second as if you prestiged": "每秒获得代币和奖章，就像您享有声望一样",
    "Get a free": "免费获得",
    "gives a free level to": "提供免费级别",
    "gives free": "免费赠送",
    "gives free levels to": "提供免费等级",
    "Goal": "目标",
    "Gödel": "哥德尔",
    "Hilbert": "希尔伯特",
    "in challenge 4": "在挑战 4",
    "Iwasawa": "岩泽",
    "Jacobsin": "雅各布辛",
    "level": "等级",
    "level per milestone": "每个里程碑级别",
    "levels": "等级",
    "levels and challenge 34 reward effects": "等级和挑战 34 种奖励效果",
    "levels and each upgrade adds .01 to the": "等级，每次升级都会增加 0.01",
    "levels, and remove": "等级，并移除",
    "levels, remove": "等级，移除",
    "linear scaling": "线性缩放",
    "linear scaling, and get a free": "线性缩放，并获得免费",
    "medal and base": "奖牌和基地",
    "medal gain and": "奖牌获得和",
    "Medals": "奖牌",
    "Milestones": "里程碑",
    "milestones require half as many goals to unlock": "里程碑需要一半的目标才能解锁",
    "NG+++ Discord": "NG+++ Discord",
    "Omnipotent I": "万能 I",
    "Omnipotent II": "万能 II",
    "Omnipotent III": "万能 III",
    "ON": "在",
    "Once per second, automatically complete": "每秒一次，自动完成",
    "Per": "每",
    "Per milestone squared add .01 to the": "每个里程碑平方添加 .01 到",
    "Per upgrade, gain 1.1x medals and gain 1.25^upgrades more": "每次升级，获得 1.1x 奖牌并获得 1.25^升级 更多",
    "Remove the ability to": "删除能力",
    "Remove the first Amoeba effect softcap": "去掉第一个变形虫效果软上限",
    "Amount": "数量",
    "adds .01 to its base and double": "将 0.01 添加到其基数和双倍",
    "adds .01 to the": "将 .01 添加到",
    "adds levels to": "将等级添加到",
    "gain": "增益",
    "Cost": "成本",
    "Buyables": "可购买",
    "Business": "商业",
    "and adds .01 to the base": "并将 0.01 添加到基数",
    "buyable,": "可购买,",
    "buyables": "可购买",
    "buyables and each": "可购买和每个",
    "buyables cost nothing": "可购买不花钱",
    "buyables once per second and each upgrade in this row allows": "可购买 每秒一次，并且该行中的每次升级都允许",
    "buyables which both give free levels to": "都提供免费等级的可购买",
    "Each Bacteria upgrade adds .1 to the": "每次细菌升级都会增加 .1",
    "Each buyable gives free levels to all previous layers corresponding buyable": "每个可购买都为对应可购买物品的所有先前层提供免费级别",
    "effect is 1": "效果是 1",
    "Give free": "免费赠送",
    "Access gives free After levels": "访问提供免费之后级别",
    "Account": "账户",
    "Add to the": "添加到",
    "adds .001 to": "将 .001 添加到",
    "All previous layer buyables have no effect": "所有之前的层可购买都没有效果",
    "and all previous prestige effects are 1": "并且之前所有的声望效果都是1",
    "and square root point gain": "和平方根点数增益",
    "Autobuy": "自动购买",
    "can buy twice as much per upgrade in this row and unlock a fourth Amoeba buyable": "在这一行中每次升级可以购买两倍并解锁第四个可购买的变形虫",
    "challenge completion adds .1 to the": "挑战完成增加 0.1",
    "Challenge completions are not reset unless said so, and you can bulk complete challenges": "除非另有说明，否则挑战完成不会重置，您可以批量完成挑战",
    "Challenges": "挑战",
    "Completed": "已完成",
    "Keep the first two rows of Amoeba upgrades and unlock more": "保留前两排变形虫升级，解锁更多",
    "Keep the third and fourth rows of Amoeba upgrades and buy each Amoeba buyable once per second": "保持第三排和第四排变形虫升级，每秒购买每个变形虫可购买一次",
    "Remove the ability to prestige but gain 100% of Bacteria on prestige per second": "移除声望的能力，但每秒获得 100% 的细菌",
    "Unlock a Bacteria buyable and get a free": "解锁可购买的细菌并免费获得",
    "Unlock the eighth Amoeba buyable": "解锁第八个可购买的变形虫",
    "Unlock the fifth Amoeba buyable and each Amoeba upgrade gives a free": "解锁第五个可购买的变形虫，每次升级变形虫都会免费获得",
    "Unlock the final": "解锁决赛",
    "Unlock the first Bacteria challenge": "解锁第一个细菌挑战",
    "Unlock two": "解锁两个",
    "Unlock two new": "解锁两个新",
    "upgrade adds .2 to the": "升级将 .2 添加到",
    "You have completed 80 Bacteria Challenges": "您已完成 80 次细菌挑战",
    "autobuyers to buy 2x more": "自动购买者购买 2 倍以上",
    "autobuyers trigger twice as often": "自动购买者触发的频率是两倍",
    "Bacteria boosts Amoeba gain": "细菌促进阿米巴的生长",
    ", which gives free levels to all": "，它为所有人提供免费等级",
    "reset": "重置",
    "reset allows you to keep one Medal upgrade": "重置允许您保留一个奖牌升级",
    "reset allows you to keep three medal milestones": "重置允许您保留三个奖牌里程碑",
    "Reset for 2 Hearts": "重置为 2 颗心",
    "Rewards": "奖励",
    "Square the successfully deved boost to Max Charges": "平方成功开发的最大充电提升",
    "squared add 1 to": "平方加 1",
    "Start with 40 Rebirths and keep": "从 40 次重生开始并保持",
    "Start with 50 Rebirths and double base": "从 50 次重生和双基地开始",
    "Start with one of each token": "从每个令牌之一开始",
    "Terraria": "泰拉瑞亚",
    "Tetris": "俄罗斯方块",
    "The first row of games each generate one charge per minute.": "第一排游戏每分钟产生一次充电。",
    "There are twenty games which progressively unlock.": "有二十款游戏逐步解锁。",
    "This fail rate is purely based on how much progress you have made so far.": "这个失败率完全取决于你到目前为止取得了多少进展。",
    "Times": "时代",
    "Total": "全部的",
    "Unlock a Medal upgrade": "解锁勋章升级",
    "Unlock a Medal upgrade and unlock a": "解锁勋章升级并解锁",
    "Unlock a new row of Medal upgrades": "解锁新的一排勋章升级",
    "Unlock a row of": "解锁一排",
    "Unlock a third": "解锁第三个",
    "Unlock another row of": "解锁另一排",
    "Unlock Game Rebirth and double base": "解锁游戏重生和双基地",
    "Unlock the second Bacteria Challenge": "解锁第二个细菌挑战",
    "upgrade gives a free": "升级免费",
    "upgrade multiply base": "升级乘数基数",
    "upgrades": "升级",
    "upgrades and": "升级和",
    "upgrades and 5x the chance to succeed": "升级和 5 倍的成功机会",
    "Upon rebirthing you lose game progress.": "重生后，您将失去游戏进度。",
    "Increase the": "增加",
    "Keep": "保持",
    "Keep all Amoeba upgrades, square": "保持所有变形虫升级，正方形",
    "Keep all Medal upgrades, milestones, and tokens": "保留所有勋章升级、里程碑和代币",
    "Keep one": "保留一个",
    "Keep this upgrade and make": "保持此升级并制作",
    "Keep three rows of Bacteria upgrades, raise": "保持三排细菌升级，养",
    "level and keep the fourth row of Bacteria upgrades": "等级并保持第四排细菌升级",
    "level per upgrade in this row": "此行中每次升级的等级",
    "levels and": "等级和",
    "levels and all autobuyers buy 100x more": "等级和所有自动购买者购买 100 倍以上",
    "levels and multiply Circle gain by the number of Circle upgrades": "等级并将圈子增益乘以圈子升级的数量",
    "levels and one to the": "等级和一个",
    "levels and unlock a": "等级并解锁",
    "levels and unlock the seventh": "等级并解锁第七个",
    "log(Games) boosts base medal gain": "log(Games) 提升基数奖牌增益",
    "log10(10+medals) boosts base": "log10(10+奖牌) 提升基数",
    "Max charges ^1.3": "最高收费 ^1.3",
    "milestone multiplies medal gain by 1.5": "里程碑将奖牌增益乘以 1.5",
    "milestone per": "每里程碑",
    "Minecraft": "我的世界",
    "Multiply": "乘",
    "Multiply base": "乘基",
    "no longer costs games": "不再花费游戏",
    "Omnipotent IV": "万能四",
    "Omntipotent I": "全能我",
    "Once per second attempt to Rebirth I": "每秒一次尝试重生 I",
    "Pac-man": "吃豆人",
    "Per milestone squared get an effective fully deved level and add 1 to base charge gain": "每个里程碑平方获得一个有效的完全开发等级，并在基数充电增益上增加 1",
    "Per upgrade double base": "每次升级双底",
    "Per upgrade multiply base": "每次升级乘数基数",
    "Per upgrade squared add one to": "每升级平方加一",
    "Per upgrade squared multiply base": "每次升级平方乘基",
    "Pokemon": "口袋妖怪",
    "Pong": "乒乓",
    "Portal": "门户网站",
    "Press shift to see success chances.": "按 shift 查看成功机会。",
    "Raise all prior prestige gain ^1.001 and double medal gain": "提高所有先前的声望增益 ^1.001 和双倍勋章增益",
    "Raise charge gain ^1.1": "提升冲锋增益 ^1.1",
    "Raise charge gain ^1.1 and be able to automatically attempt to bulk dev each game once per second": "提高充电增益 ^1.1 并能够每秒自动尝试批量开发每个游戏一次",
    "Raise charge gain ^1.1 and buff Base G gain from rebirths": "提高冲锋增益 ^1.1 并增强重生的基数 G 增益",
    "Raise charge gain ^1.1 and shift can bulk 10x more": "提高电荷增益 ^1.1 并且移位可以增加 10 倍以上",
    "Raise charge gain ^1.1 and the first four games do not cost charges": "提升冲锋增益^1.1，前四场不消耗冲锋",
    "Raise charge gain ^1.1 and triple base": "提高电荷增益 ^1.1 和三倍基数",
    "Raise charge gain ^1.1, deving costs 10x less charges, and each Rebirth doubles max charges": "提升冲锋增益 ^1.1，开发成本降低 10 倍，每次重生使最大冲锋翻倍",
    "Raise charge gain ^1.1, triple maximum charges, and attempting to dev a game no longer costs games": "提高冲锋增益 ^1.1，三倍最大冲锋，尝试开发游戏不再花费游戏",
    "Raise charge gain ^1.2 and 6x max charges": "提高冲锋增益 ^1.2 和 6 倍最大冲锋",
    "Raise charge gain per minute ^1.2 and hold shift to attempt buy 10 clickables": "提高每分钟的充电增益 ^1.2 并按住 shift 以尝试购买 10 个可点击",
    "Raise charge gain per minute ^1.2 and sqrt(Charges) multiplies": "提高每分钟的电荷增益 ^1.2 和 sqrt(Charges) 倍增",
    "Rebirth": "重生",
    "Rebirth I": "重生我",
    "Rebirthing makes attempting to dev harder and causes it to consume more charges.": "重生使尝试开发变得更加困难，并导致它消耗更多费用。",
    "Remove the ability to prestige but gain 100% of Circles on prestige per second": "移除声望的能力，但每秒获得 100% 的声望圈数",
    "Remove the ability to prestige but gain 100% of Doodles on prestige per second and unlock a": "移除声望的能力，但每秒获得 100% 的声望涂鸦并解锁一个",
    "Remove the ability to prestige but gain 100% of Games on prestige per second": "移除声望的能力，但每秒获得 100% 的游戏声望",
    "Remove the first Bacteria effect softcap": "去掉第一个细菌效果软帽",
    "Remove the G gain exponent softcap": "移除 G 增益指数软帽",
    "Remove the medal gain softcap and each successful dev adds .01 to the": "移除奖牌获得软上限，每个成功的开发者都会增加 0.01",
    "Remove the successful dev boost to Feature gain softcap": "移除对功能增益软上限的成功开发提升",
    "Remove the successful dev boost to Game gain softcap": "移除对游戏增益软上限的成功开发提升",
    "Remove the successful dev boost to Medal gain softcap": "取消对奖牌增益软上限的成功开发提升",
    "Requires": "需要",
    "Each attempts costs 2.08e23 charges.": "每次尝试花费 2.08e23 费用。",
    "Each Bacteria upgrade gives a free": "每次细菌升级都会免费提供",
    "Each completion gives tokens": "每个完成都会给出令牌",
    "Each milestone adds 1 to base charge gain and half an effective Rebirth level": "每个里程碑增加 1 基数充能增益和一半有效重生等级",
    "Each milestone gives two free": "每个里程碑免费赠送两个",
    "Each milestone raises max charges ^1.1 and multiply base charge gain by 1.2": "每个里程碑都会提高最大冲锋 ^1.1 并将基数冲锋增益乘以 1.2",
    "Each upgrade adds 1 to effective rebirths": "每次升级都会增加 1 次有效重生",
    "Each upgrade adds 1 to the Medal gain exponent": "每次升级都会使奖牌获得指数增加 1",
    "Each upgrade adds 78 to": "每次升级增加 78",
    "Each upgrade in this row unlocks a": "此行中的每次升级都会解锁一个",
    "Each upgrade in this row unlocks a rebirth reward": "此行的每次升级都会解锁重生奖励",
    "Each upgrade in this row unlocks an": "此行中的每次升级都会解锁一个",
    "Each upgrade multiplies base": "每次升级都会增加基数",
    "effect and double medal gain per milestone": "每个里程碑的效果和双倍奖牌增益",
    "effect exponent by +.1": "+.1 的影响指数",
    "effect to the number of Bacteria upgrades, and unlock a Amoeba buyable": "影响细菌升级数量，并解锁可购买的变形虫",
    "For the first row, you no matter what will gain a level,": "对于第一行，你无论如何都会获得一个级别，",
    "gain and you can bulk 4x more": "增益，你可以批量增加 4 倍",
    "gain base": "获得基数",
    "gain based on best": "基于最佳收益",
    "Game resetting no longer forces you into challenge 00, keep tokens, and unlock Games": "游戏重置不再强迫您挑战 00、保留代币和解锁游戏",
    "Goals multiply base": "目标倍增基数",
    "C0: Nothing": "C0：没有",
    "C1: Raise all prestige gains ^.985 + C0": "C1：提高所有声望增益^.985 + C0",
    "C2: Raise point, Egg, and Feature gain ^.9 + C1": "C2：提升点、蛋和特征增益 ^.9 + C1",
    "C3: First column buyables do not give effects in the first n layers": "C3：第一列可购买物品不会在前 n 层产生影响",
    "C4: No buyables give free levels to buyables in the first n layers": "C4：没有可购买物为前 n 层的可购买物提供免费关卡",
    "challenge": "挑战",
    "Challenge AB means you are in Challenge A twice and Challenge B once": "挑战 AB 意味着您参加了两次挑战 A 和一次挑战 B",
    "challenge and": "挑战和",
    "challenge completions squared add to the": "挑战完成平方增加",
    "challenge, and gain 100x points": "挑战，获得100倍积分",
    "challenges if you have enough points and Goals^Goals multiply": "如果你有足够的分数和目标^目标成倍增加",
    "Clicking a game will consume a charge.": "点击游戏会消耗费用。",
    "Complete a challenge by medal resetting, which requires": "通过重置奖牌完成挑战，这需要",
    "Completion": "完成",
    "Completion of a challenge gives a token to that \"upgrade\" which gives an effect": "挑战的完成会为该“升级”提供一个令牌，该“升级”会产生效果",
    "Double charge gain and holding shift allows 10x more game attempts": "双倍充电增益和保持转移允许 10 倍以上的游戏尝试",
    "Double the chance to succeed, raise charges gain ^1.1, keep": "加倍成功机会，提高冲锋获得 ^1.1，保持",
    "all prior unlocked main layers are totally reset, and goals are also reset": "所有之前解锁的主层都被完全重置，目标也被重置",
    "Always act as if you are in medal challenge 00": "总是表现得好像你在挑战奖牌 00",
    "and adds .1 to the": "并将 .1 添加到",
    "and Challenge 22 means you are in challenge 2 twice and challenge 2 once,": "挑战 22 表示您参加了两次挑战 2 和一次挑战 2，",
    "and larger buffs for completing games.": "以及用于完成游戏的更大增益。",
    "and raise": "并提高",
    "and square root": "和平方根",
    "and three rows of": "和三排",
    "and unlock a": "并解锁一个",
    "and want to enter challenge 00 to avoid softlocking": "并想进入挑战 00 以避免软锁定",
    "Autobuyers are 3x faster and buy 10x more": "自动购买者的速度提高了 3 倍，购买速度提高了 10 倍",
    "autobuyers buy 3x faster": "自动购买者的购买速度提高了 3 倍",
    "autobuyers can buy 10x more": "自动购买者可以多买 10 倍",
    "Autochess": "自走棋",
    "Automatically buy": "自动购买",
    "base and .2 to the": "基数和 .2 到",
    "base, and unlock upgrades": "基地，并解锁升级",
    "but for subsequent rows you have a non-zero chance of failing and gaining nothing.": "但是对于随后的行，您失败且一无所获的机会非零。",
    "Buy": "买",
    "buyable": "可买的",
    "buyable and": "可购买和",
    "buyable, and buyable autobuyers bulk is multiplied by medals": "可购买的，可购买的自动购买者批量乘以奖牌",
    "buyable, remove": "可购买，删除",
    "buyables cost nothing, each goal adds .002 to the": "可购买的东西不花钱，每个目标都会增加 0.002",
    "buyables don't cost anything, and keep": "可购买的东西不花任何钱，并且保持",
    "buyables once per second and": "每秒一次的可购买物品和",
    "buyables squared multiply": "可购买的平方乘",
    "buyables, unlock the final": "可买的，解锁决赛",
    "Your maximum charges is 100 and raise charge gain per minute ^1.2": "您的最大充能数为 100 并提高每分钟的充能增益 ^1.2",
    "You can also autobuy the first four games": "您还可以自动购买前四场比赛",
    "You can gain buffs by partially deving games,": "您可以通过部分开发游戏来获得增益，",
    "You can rebirth when you have fully deved 16 games.": "当您完全开发了 16 款游戏时，您可以重生。",
    "Gain one free Rebirth level": "获得一个免费的重生等级",
    ", and gain 2 charges per minute": "，并每分钟获得 2 次充电",
    "Add one to the": "添加一个到",
    "autobuyer speed": "自动购买速度",
    "level and": "水平和",
    "level and triple": "水平和三重",
    "levels and all autobuyers buy 3x faster": "水平和所有自动购买者购买速度快 3 倍",
    "levels and gain a free": "水平并获得免费",
    "ln(Charges) multiplies base": "ln(费用) 乘以基数",
    "Raise Charge gain ^1.1": "提升冲锋增益 ^1.1",
    "Raise the successfully deved boosted to Features to the 20": "将成功开发的功能提升到 20",
    "Remove the ability to prestige but gain 100% of Eggs on prestige per second and all autobuyers work 2x faster": "移除声望的能力，但每秒获得 100% 的鸡蛋声望，所有自动购买者的工作速度提高 2 倍",
    "Square the successfully deved boosted to Max Charges": "将成功开发的平方提升到最大电荷",
    "Unlock a fully completed effect": "解锁完全完成的效果",
    "upgrade multiplies base medal gain by 12 and adds 34 to the exponent": "升级将基数奖牌增益乘以 12 并在指数上增加 34",
    "upgrades, autobuy": "升级，自动购买",
    "buyable and each upgrade in this row unlocks a": "可购买，并且该行中的每次升级都会解锁一个",
    "buyables and autobuy": "可购买物品和自动购买",
    "buyables once per second": "每秒一次的可购买物品",
    "buyables once per second, and multiply all autobuyer bulk by the number of goals": "每秒一次可购买，并将所有自动购买批量乘以目标数量",
    "Details": "详情",
    "Eggs": "蛋",
    "Energy": "能源",
    "Entertainment": "娱乐",
    "Event": "事件",
    "Omnipotent V": "万能 V",
    "all prior prestige gain exponents": "所有先前的声望增益指数",
    "Click a button below to enter a challenge": "点击下方按钮进入挑战",
    "base per": "基数每",
    "boosts base": "提升基数",
    "cost and": "成本和",
    "and": "和",
    "Category": "类别",
    "base": "基数",
    "Card": "卡片",
    "Country": "国家",
    "Database": "数据库",
    "Delivery": "交付",
    "Department": "部门",
    "December": "十二月",
    "at least one token for the challenge\n                                        to the left and above": "至少一个用于挑战\n左侧和上方的代币",
    "Diophantine": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "This is my (pg132's) first fully completed mod, I may have another coming. Consider playing the other game I currently dev, AD NG+++: ": "这是我（pg132 的）第一个完全完成的 mod，我可能还会有另一个。 考虑玩我目前开发的另一个游戏，AD NG+++：",
    "The Prestige Tree made by Jacorb and Aarex": "Jacorb 和 Aarex 制作的声望树",
    "Change log": "更新日志",
    "Congratulations! You have reached the end and beaten this game!": "恭喜！ 你已经到达终点并通关了本游戏！",
    "Endgame: 378 achievements": "残局：378 项成就",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
//    'ON': '打开',
    'On': '打开',
    'Off': '关闭',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置',
    'Nine': '9',
    'Nineteen': '19',
    'One': '1',
    'Seven': '7',
    'Seventeen': '17',
    'Thirteen': '13',
    'Sixteen': '16',
    'Ten': '10',
    'Thirty': '30',
    'eight': '8',
    'five': '5',
    'four': '4',
    'nine': '9',
    'one': '1',
    'seven': '7',
    'six': '6',
    'three': '3',
    'two': '2',
    'Three': '3',
    'Twelve': '12',
    'Twenty': '20',
    'Two': '2',
    'Fourteen': '14',
    'Four': '4',
    'Six': '6',
    'Fifty': '50',
    'Fifteen': '15',
    'Eighteen': '18',
    'Eleven': '11',
    'Five': '5',
    'Forty': '40',
    'Ninety': '90',
    'Seventy': '70',
    'Sixty': '60',
    'Eighty': '80',
    'One': '01',
    'Two': '02',
    'Three': '03',
    'Four': '04',
    'Five': '05',
    'Six': '06',
    'Seven': '07',
    'Eight': '08',
    'Nine': '09',
    'Four Hundred': '4',
    'One Hundred': '100',
    'Two Hundred': '200',
    'Three Hundred': '300',
    'Five Hundred': '500',
    'Six Hundred': '600',
    'Seven Hundred': '700',
    'DNA': 'DNA',
    'Micro': 'Micro',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\t\t\t\t\t\t\t": "\t\t\t\t\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t": "\t\t\t",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "There is a two second cooldown for prestiging (": "声望有两秒的冷却时间（",
    ", which buffs point and all previous prestige gain by ": ", 增益点和之前的所有声望都会增加",
    "Each Amoeba Upgrade multiplies Amoeba gain by ": "每次 变形虫 升级都会使 变形虫 增益乘以",
    "Shift/Control Mode:": "变速/控制模式：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Seven Hundred and ": "7",
    "Thirty-": "3",
    "Twenty-": "2",
    "Forty-": "4",
    "Eighty-": "8",
    "Ninety-": "9",
    "Fifty-": "5",
    "Seventy-": "7",
    "Sixty-": "6",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n\t\t": "\n\t\t",
    "\n": "",
    "/sec": "/秒",
    " nice": " 不错",
    " affects Life Points": "影响生命点",
    ") times multipliers": ") 次乘数",
    "\n\t\t\t": "\n\t\t\t",
    "\n\t\t\t\t": "\n\t\t\t\t",
    "Each challenge has a reward, and upon claiming said reward": "每个挑战都有一个奖励，并在领取所述奖励时",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\)\*([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^\*([\d\.]+)e(\d+)$/,
    /^([\d\.]+)e(\d+) µ$/,
    /^([\d\.]+)e(\d+) OOMs$/,
    /^([\d\.]+)e(\d+) 细胞$/,
    /^([\d\.]+)e(\d+) 干细胞$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)\/m$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)ms$/,
    /^([\d\.]+)$/,
    /^C([\d\.]+)$/,
    /^e([\d\.,]+)$/,
    /^EXTREME: (.+)$/,
    /^α → (.+)$/,
    /^β → (.+)$/,
    /^𝛾 → (.+)$/,
    /^µ → (.+)$/,
    /^([\d\.]+)\^x$/,
    /^([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^\^e([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+) µ$/,
    /^([\d\.]+)e([\d\.,]+) µ$/,
    /^ee([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^\*e([\d\.]+)e([\d\.,]+) to$/, '\*e$1e$2 到'],
    [/^Requires: (.+) Cells$/, '要求：$1 细胞'],
    [/^Last save was (.+)s ago.$/, '上次保存是在 $1 秒前。'],
    [/^Last save was (.+)s ago. Average TPS (.+).$/, '上次保存是在 $1 秒前。 平均 $2。'],
    [/^Get a (.+) Gem$/, '获得 1个 $1 宝石'],
    [/^Reset for (.+) Amoebas$/, '重置为 $1 变形虫'],
    [/^You have done (.+) Amoeba resets$/, '您已完成 $1 次变形虫重置'],
    [/^Each Amoeba upgrade adds (.+) to the$/, '每次 变形虫 升级都会增加 $1 到'],
    [/^Each upgrade adds (.+) to the$/, '每次升级都会增加 $1 到'],
    [/^e([\d\.]+)e([\d\.,]+) Doodles$/, 'e$1e$2 涂鸦'],
    [/^e([\d\.]+)e([\d\.,]+) Circles$/, 'e$1e$2 圆圈'],
    [/^e([\d\.]+)e([\d\.,]+) Bacteria$/, 'e$1e$2 细菌'],
    [/^\+([\d\.]+) to$/, '\+$1 到'],
    [/^\*([\d\.]+) to$/, '\*$1 到'],
    [/^\^([\d\.]+) Are effect$/, '\^$1 效果'],
    [/^\*e([\d\.]+)e([\d\.,]+) Eggs$/, '\*e$1e$2 蛋'],
    [/^\*e([\d\.]+)e([\d\.,]+) Due base$/, '\*e$1e$2 正当基数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Category base$/, '\*e$1e$2 类别基数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Against base$/, '\*e$1e$2 反对基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) Because base$/, '\*e$1e$2 原因基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) Because base$/, '\*e$1e$2 原因基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) Circles$/, '\*e$1e$2 圈子'],
    [/^\*e([\d\.]+)e([\d\.,]+) Advanced base$/, '\*e$1e$2 高级基地'],
    [/^\*e([\d\.]+)e([\d\.,]+) points$/, '\*e$1e$2 点数'],
    [/^\*e([\d\.]+)e([\d\.,]+) Bacteria$/, '\*e$1e$2 细菌'],
    [/^\*e([\d\.]+)e([\d\.,]+) Amoebas$/, '\*e$1e$2 变形虫'],
    [/^\+([\d\.]+)e([\d\.,]+) Example base$/, '\+$1e$2 示例基地'],
    [/^\+([\d\.]+)e([\d\.,]+) Doodle gain exponent$/, '\+$1e$2 涂鸦增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) Egg gain exponent$/, '\+$1e$2 蛋增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) Access base$/, '\+$1e$2 访问基地'],
    [/^\+([\d\.]+)e([\d\.,]+) Circle gain exponent$/, '\+$1e$2 圆圈增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) Amoeba gain exponent$/, '\+$1e$2 变形虫增益指数'],
    [/^\+([\d\.]+)e([\d\.,]+) B gain exp$/, '\+$1e$2 B 增益指数'],
    [/^You are gaining (.+) Games per second$/, '您每秒获得 $1 游戏'],
    [/^You are gaining (.+) Features per second$/, '您每秒获得 $1 功能'],
    [/^You have (.+) charges and are gaining (.+) per second.$/, '你有 $1 充能，每秒获得 $2。'],
    [/^You have (.+) games, (.+) medals, (.+) goals, and (.+) features.$/, '您有 $1 场比赛、$2 枚奖牌、$3 个进球和 $4 个特征。'],
    [/^You have successfully deved (.+) games so$/, '您已经成功开发了 $1 款游戏，所以'],
    [/^You have rebirthed (.+) times.$/, '你重生了 $1 次。'],
    [/^You have rebirthed (.+) times so$/, '你重生了 $1 次所以'],
    [/^You have fully completed (.+) games so$/, '你已经完全完成了 $1 场比赛所以'],
    [/^You have done (.+) Heart resets$/, '你已经完成了 $1 次心脏重置'],
    [/^You have completed (.+) Circle Challenges$/, '您已完成 40 个圈子挑战'],
    [/^You are gaining (.+) Eggs per second$/, '您每秒获得 $1 鸡蛋'],
    [/^and (.+) tokens$/, '和 $1 代币'],
    [/^gain, currently: (.+)$/, '增益，当前：$1'],
    [/^gain by ([\d\.]+)$/, '增益 $1'],
    [/^Reset for (.+) Medals$/, '重置为 $1 奖牌'],
    [/^Next at (.+) points$/, '下一个在 $1 点'],
    [/^Get (.+) Organs$/, '获得 $1 器官'],
    [/^e([\d\.]+)e([\d\.,]+) Eggs$/, 'e$1e$2 蛋'],
    [/^e([\d\.]+)e([\d\.,]+) Amoebas$/, 'e$1e$2 变形虫'],
    [/^Gems: (.+)$/, '宝石：$1'],
    [/^Get (.+) Dilation completions$/, '获得 $1 扩张完成'],
    [/^Get (.+) Oxygenated Blood$/, '获得 $1 含氧血'],
    [/^Get (.+) Hydrogen$/, '获得 $1 氢'],
    [/^Get (.+) Atomic Hydrogen$/, '获得 $1 原子氢'],
    [/^Requires: ([\d\.,]+) Completed games$/, '需要: $1 已完成的游戏'],
    [/^Requires: ([\d\.,]+) Games$/, '需要: $1 游戏'],
    [/^Requires: ([\d\.,]+) ([\d\.,]+) Token$/, '需要: $1 $2 代币'],
    [/^Requires: ([\d\.,]+) Successful devs$/, '需要: $1 成功的开发者'],
    [/^Requires: ([\d\.,]+) Medal$/, '需要: $1 奖章'],
    [/^Requires: ([\d\.,]+) Hearts$/, '需要: $1 心'],
    [/^Requires: ([\d\.,]+) Medals$/, '需要: $1 奖牌'],
    [/^Requires: ([\d\.,]+) Rebirth I$/, '需要: $1 重生 I'],
    [/^Requires: ([\d\.,]+)\% Completion on Portal$/, '需要: $1\% 在门户网站上完成'],
    [/^Requires: ([\d\.,]+) ([\d\.,]+) Tokens$/, '需要: $1 $2 代币'],
    [/^Cost: ([\d\.,]+)$/, '成本: $1'],
    [/^Cost: ([\d\.,]+) $/, '成本: $1 '],
    [/^Cost: ([\d\.]+)e([\d\.,]+)$/, '成本: $1e$2'],
    [/^Cost: ([\d\.]+)e([\d\.,]+) $/, '成本: $1e$2 '],
    [/^Cost: e([\d\.]+)e([\d\.,]+) $/, '成本: e$1e$2 '],
    [/^Goal: e([\d\.]+)e([\d\.,]+) points$/, '目标: e$1e$2 点数'],
    [/^Cost: (.+) Deuterium$/, '成本: $1 氘'],
    [/^Cost: (.+) Organs$/, '成本: $1 器官'],
    [/^Time Played: (.+)s$/, '游戏时长：$1 秒'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);